### ISSUE TITLE
Questions regarding nat_node->addr_parse()

### ISSUE THREAD

**Issue by waynemystir** [mwarning/UDP-hole-punching-examples#1]
Hi @mwarning

Thank you for posting this repo. This example is very helpful. I have a couple questions regarding the second example, nat_node.c.

In the method addr_parse(), you set hints.ai_socktype = SOCK_STREAM. I wonder if it should be set to SOCK_DGRAM instead?

Also, in the while loop, you never set p = p->next. So you expect there to be a single addr_info from getaddrinfo? If that's the case, why make this a while loop rather than an if statement?

I really appreciate any help you can give me @mwarning . And again, thank you for posting this very helpful example!

Thanks,

Wayne

**Comment by mwarning** [comment]
`hints.ai_socktype = SOCK_STREAM` probably does not matter. But SOCK_DGRAM would be nicer.
The missing p = p->next is a bug. Nice find. :-)

**Comment by mwarning** [comment]
@waynemystir the issue should be fixed now. Thanks!

**Comment by waynemystir** [comment]
Thank you @mwarning !
